In [110]:
import boto3
import pandas as pd
import random
from datetime import timedelta
# !pip install python-dotenv
from dotenv import load_dotenv
import os
import json
from numpy.distutils.fcompiler import none

In [111]:
load_dotenv()

True

In [112]:
print(os.getenv("AWS_ACCESS_KEY_ID"))

AKIA2D6AFAAEWSSJBHXX

In [113]:
AD_IDS=[f"AD{i} " for i in range(1,21)]

file_path="E:\AD-TECH PROJECT\Online Retail.xlsx"
df=pd.read_excel(file_path)
# print(df.head())

In [119]:
df=df.dropna(subset=['Quantity', 'InvoiceDate','UnitPrice', 'CustomerID'])
df["amount"]=df["Quantity"]*df['UnitPrice']

df=df.rename(columns={"CustomerID":"user_id","InvoiceDate":"timestamp"})

df=df[["user_id","timestamp","amount"]]

C:\Users\Hp\AppData\Local\Temp\ipykernel_28976\1106803260.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["amount"]=df["Quantity"]*df['UnitPrice']

In [128]:
df.head(10)

   user_id           timestamp  amount
0  17850.0 2010-12-01 08:26:00   15.30
1  17850.0 2010-12-01 08:26:00   20.34
2  17850.0 2010-12-01 08:26:00   22.00
3  17850.0 2010-12-01 08:26:00   20.34
4  17850.0 2010-12-01 08:26:00   20.34
5  17850.0 2010-12-01 08:26:00   15.30
6  17850.0 2010-12-01 08:26:00   25.50
7  17850.0 2010-12-01 08:28:00   11.10
8  17850.0 2010-12-01 08:28:00   11.10
9  13047.0 2010-12-01 08:34:00   54.08

In [83]:
# ad_user=random.random()>0.7
# print(ad_user)

num_events=random.randint(2,4)
print(num_events)

4

In [84]:
def generate_journey(row):

    user=row["user_id"]
    purchase_time=row["timestamp"]
    events=[]

    ad_user=random.random()<0.7
    current_time=purchase_time


    if ad_user:
        num_events=random.randint(2,4)

        for i in range(num_events):
            current_time -=timedelta(minutes=random.randint(5,20))

            event_type=random.choice(["impression","click","browse"])
            events.append({
                "user_id":user,
                "timestamp":current_time.strftime("%Y-%m-%d %H:%M:%S"),
                "event":event_type,
                "ad_id":random.choice(AD_IDS),
                "amount":None
            })


    events.append({
        "user_id":user,
        "timestamp":purchase_time.strftime("%Y-%m-%d %H:%M:%S"),
        "amount":row["amount"],
        "event":"purchase",
        "ad_id":None
    })

    return events

In [85]:
all_events=[]

In [86]:
for _,row in df.iterrows():
    journey=generate_journey(row)
    all_events.extend(journey)

In [87]:
for i in range(1000):
    user = f"U_fake_{i}"
    current_time = pd.Timestamp("2026-04-01 10:00:00")

    for j in range(random.randint(2, 5)):
        current_time += timedelta(minutes=random.randint(5, 15))

        all_events.append({
            "user_id": user,
            "event": random.choice(["impression", "click", "browse"]),
            "ad_id": random.choice(AD_IDS),
            "timestamp": current_time.strftime("%Y-%m-%d %H:%M:%S"),
            "amount": None
        })

list

In [88]:
all_events=sorted(all_events,key=lambda x:x["timestamp"])

In [89]:
type(all_events)

list

In [90]:
s3=boto3.client("s3")

s3.put_object(
    Bucket="ad-tech-click",
    Key="events/data.json",
    Body=json.dumps(all_events),
    ContentType="application/json"
)

{'ResponseMetadata': {'RequestId': 'Z75N7AB9RBBMB7X5',
  'HostId': 'g3LZFPDEYThSXlwryXDUJhsACYcaYuUVq7zaFc8RhEndh9PzE0/7K8cS05iCSWJzkdnaZfk3i6c+T/P47GBHORfVKtAxxLQn',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'g3LZFPDEYThSXlwryXDUJhsACYcaYuUVq7zaFc8RhEndh9PzE0/7K8cS05iCSWJzkdnaZfk3i6c+T/P47GBHORfVKtAxxLQn',
   'x-amz-request-id': 'Z75N7AB9RBBMB7X5',
   'date': 'Sat, 04 Apr 2026 09:39:04 GMT',
   'x-amz-version-id': 'aqDT2whGeyoSnJp8v0Uyxa3KXpWi87Em',
   'x-amz-server-side-encryption': 'AES256',
   'etag': '"148a569090a8e23fe1c26f72fe66e836"',
   'x-amz-checksum-crc32': 'Cp5MGw==',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 1},
 'ETag': '"148a569090a8e23fe1c26f72fe66e836"',
 'ChecksumCRC32': 'Cp5MGw==',
 'ChecksumType': 'FULL_OBJECT',
 'ServerSideEncryption': 'AES256',
 'VersionId': 'aqDT2whGeyoSnJp8v0Uyxa3KXpWi87Em'}

In [101]:
df1=pd.DataFrame(all_events)

In [102]:
df1.head()

   user_id            timestamp       event  ad_id  amount
0  13047.0  2010-12-01 07:30:00  impression   AD2      NaN
1  17850.0  2010-12-01 07:36:00  impression  AD15      NaN
2  17850.0  2010-12-01 07:43:00       click   AD1      NaN
3  13047.0  2010-12-01 07:45:00       click   AD3      NaN
4  13047.0  2010-12-01 07:47:00      browse  AD15      NaN

In [108]:
df1["amount"].isna().sum()

np.int64(858278)

In [109]:
df1["amount"].isna().value_counts().rename({
    True: "missing",
    False: "present"
})

amount
missing    858278
present    406829
Name: count, dtype: int64